// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCdm9ry7QO1_AQ-qWT-gy8MM-VXYayitpY',
    appId: '1:336335118739:web:1ac556bc53f88dcc854866',
    messagingSenderId: '336335118739',
    projectId: 'healthiq-22f01',
    authDomain: 'healthiq-22f01.firebaseapp.com',
    storageBucket: 'healthiq-22f01.firebasestorage.app',
    measurementId: 'G-17PT2X8QQ3',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC65SU7Ydesk8weVhf5dzA0lI9F1BnlVA8',
    appId: '1:336335118739:android:0fc8084dd049a164854866',
    messagingSenderId: '336335118739',
    projectId: 'healthiq-22f01',
    storageBucket: 'healthiq-22f01.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDUi1DxMf8O-F8izDUZ_Yqb_4tVW8JJjy0',
    appId: '1:336335118739:ios:d66b7df8441d58f1854866',
    messagingSenderId: '336335118739',
    projectId: 'healthiq-22f01',
    storageBucket: 'healthiq-22f01.firebasestorage.app',
    androidClientId: '336335118739-2b497a6p4scv3tacfs5e6kosobmv7uud.apps.googleusercontent.com',
    iosClientId: '336335118739-so8bocgjk88e8fr0mted926oai4vg2vg.apps.googleusercontent.com',
    iosBundleId: 'com.example.healthiq',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDUi1DxMf8O-F8izDUZ_Yqb_4tVW8JJjy0',
    appId: '1:336335118739:ios:d66b7df8441d58f1854866',
    messagingSenderId: '336335118739',
    projectId: 'healthiq-22f01',
    storageBucket: 'healthiq-22f01.firebasestorage.app',
    androidClientId: '336335118739-2b497a6p4scv3tacfs5e6kosobmv7uud.apps.googleusercontent.com',
    iosClientId: '336335118739-so8bocgjk88e8fr0mted926oai4vg2vg.apps.googleusercontent.com',
    iosBundleId: 'com.example.healthiq',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCdm9ry7QO1_AQ-qWT-gy8MM-VXYayitpY',
    appId: '1:336335118739:web:c8f3109c0587a857854866',
    messagingSenderId: '336335118739',
    projectId: 'healthiq-22f01',
    authDomain: 'healthiq-22f01.firebaseapp.com',
    storageBucket: 'healthiq-22f01.firebasestorage.app',
    measurementId: 'G-JRSQYRLKTY',
  );
}
